name: New Version

on:
  push:
    branches: [main]
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build with VitePress
        run: npm run docs:build

      - name: Create a new version
        env:
          REF: ${{ github.ref }}
        run: |
          mkdir versions/${REF:10}
          mv docs versions/${REF:10}/
          mv index.md versions/${REF:10}/
          mv .vitepress versions/${REF:10}/
          sed -i "s|/docs/|/${REF:10}/docs/|g" versions/${REF:10}/index.md
          sed -i "s|/docs/|/${REF:10}/docs/|g" versions/${REF:10}/.vitepress/config.mjs
          find versions/${REF:10} -type f -exec sed -i "s|/assets/images/|/versions/${REF:10}/assets/images/|g" {} +

      #- name: Create a new sidebar
        #env:
          #REF: ${{ github.ref }}
        #run: |
          #cp .vitepress/sidebars/versioned/default.json .vitepress/sidebars/versioned/${REF:10}.json
          #sed -i "s|/docs/|/${REF:10}/docs/|g" .vitepress/sidebars/versioned/${REF:10}.json

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true

      - name: Commit 
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Created a new version
